variable "aws_region" {
  description = "AWS Region where the RDS environment is deployed."
  type        = string
  default     = "us-east-2"
}

variable "environment" {
  description = "Deployment environment name."
  type        = string
  default     = "dev"
}

variable "vpc_cidr" {
  description = "CIDR range for the RDS VPC."
  type        = string
  default     = "10.20.0.0/16"
}

variable "private_subnet_cidrs" {
  description = "Private subnet CIDR ranges for the RDS subnet group."
  type        = list(string)

  default = [
    "10.20.10.0/24",
    "10.20.20.0/24"
  ]

  validation {
    condition     = length(var.private_subnet_cidrs) >= 2
    error_message = "At least two private subnet CIDR ranges are required."
  }
}

variable "allowed_postgres_cidr_blocks" {
  description = "Networks permitted to connect to PostgreSQL. Leave empty until routed application or VPN networks exist."
  type        = set(string)
  default     = []
}

variable "postgres_engine_version" {
  description = "RDS PostgreSQL engine version."
  type        = string
  default     = "18.4"
}

variable "db_instance_class" {
  description = "RDS database instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "database_name" {
  description = "Initial PostgreSQL database name."
  type        = string
  default     = "mypawsbnb"

  validation {
    condition     = can(regex("^[A-Za-z][A-Za-z0-9_]*$", var.database_name))
    error_message = "The database name must begin with a letter and contain only letters, numbers, and underscores."
  }
}

variable "master_username" {
  description = "RDS administrative username. The password is generated by AWS."
  type        = string
  default     = "mypawsadmin"
}

variable "allocated_storage" {
  description = "Initial storage allocation in GiB."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Maximum storage size RDS storage autoscaling can allocate."
  type        = number
  default     = 100
}

variable "backup_retention_period" {
  description = "Number of days automated backups are retained."
  type        = number
  default     = 7
}

variable "multi_az" {
  description = "Whether to deploy the database as a Multi-AZ DB instance."
  type        = bool
  default     = false
}